# Generated by Django 3.2.3 on 2021-07-14 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210701_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='Discount',
            field=models.CharField(blank=True, default='0% Off', max_length=250),
        ),
        migrations.AlterField(
            model_name='c_payment',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 17, 21, 32, 631957)),
        ),
        migrations.AlterField(
            model_name='contact_detail',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 17, 21, 32, 625450)),
        ),
        migrations.AlterField(
            model_name='corderbooking',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 17, 21, 32, 631957)),
        ),
        migrations.AlterField(
            model_name='current_stock',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 17, 21, 32, 631957)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 17, 21, 32, 631957)),
        ),
        migrations.AlterField(
            model_name='daily_expense',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 17, 21, 32, 631957)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 17, 21, 32, 609829)),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 17, 21, 32, 609829)),
        ),
        migrations.AlterField(
            model_name='previous_experience',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 17, 21, 32, 625450)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 17, 21, 32, 631957)),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 17, 21, 32, 625450)),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 17, 21, 32, 631957)),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 17, 21, 32, 625450)),
        ),
        migrations.AlterField(
            model_name='s_contact_detail',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 17, 21, 32, 631957)),
        ),
        migrations.AlterField(
            model_name='s_contact_person',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 17, 21, 32, 631957)),
        ),
        migrations.AlterField(
            model_name='s_order_booking',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 17, 21, 32, 631957)),
        ),
        migrations.AlterField(
            model_name='s_payment',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 17, 21, 32, 631957)),
        ),
        migrations.AlterField(
            model_name='skills',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 17, 21, 32, 625450)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 17, 21, 32, 625450)),
        ),
    ]
