# Generated by Django 3.2.3 on 2021-07-15 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210714_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='COD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('PhoneNo3', models.CharField(max_length=13)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='c_payment',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 43, 16, 948003)),
        ),
        migrations.AlterField(
            model_name='contact_detail',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 43, 16, 931013)),
        ),
        migrations.AlterField(
            model_name='corderbooking',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 43, 16, 946004)),
        ),
        migrations.AlterField(
            model_name='current_stock',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 43, 16, 951001)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 43, 16, 945005)),
        ),
        migrations.AlterField(
            model_name='daily_expense',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 43, 16, 950002)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 43, 16, 924037)),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 43, 16, 925036)),
        ),
        migrations.AlterField(
            model_name='previous_experience',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 43, 16, 928015)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 43, 16, 936009)),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 43, 16, 932012)),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 43, 16, 934011)),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 43, 16, 927010)),
        ),
        migrations.AlterField(
            model_name='s_contact_detail',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 43, 16, 941006)),
        ),
        migrations.AlterField(
            model_name='s_contact_person',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 43, 16, 943007)),
        ),
        migrations.AlterField(
            model_name='s_order_booking',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 43, 16, 937009)),
        ),
        migrations.AlterField(
            model_name='s_payment',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 43, 16, 940007)),
        ),
        migrations.AlterField(
            model_name='skills',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 43, 16, 930013)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 2, 43, 16, 933012)),
        ),
    ]
