# Generated by Django 3.2.3 on 2021-07-16 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210716_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pieces',
        ),
        migrations.AlterField(
            model_name='c_payment',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 22, 48, 0, 496169)),
        ),
        migrations.AlterField(
            model_name='contact_detail',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 22, 48, 0, 485156)),
        ),
        migrations.AlterField(
            model_name='corderbooking',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 22, 48, 0, 494151)),
        ),
        migrations.AlterField(
            model_name='current_stock',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 22, 48, 0, 498148)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 22, 48, 0, 494151)),
        ),
        migrations.AlterField(
            model_name='daily_expense',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 22, 48, 0, 497149)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 22, 48, 0, 481156)),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 22, 48, 0, 482158)),
        ),
        migrations.AlterField(
            model_name='previous_experience',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 22, 48, 0, 484154)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 22, 48, 0, 488154)),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 22, 48, 0, 486156)),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 22, 48, 0, 487155)),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 22, 48, 0, 483157)),
        ),
        migrations.AlterField(
            model_name='s_contact_detail',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 22, 48, 0, 492150)),
        ),
        migrations.AlterField(
            model_name='s_contact_person',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 22, 48, 0, 493152)),
        ),
        migrations.AlterField(
            model_name='s_order_booking',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 22, 48, 0, 489153)),
        ),
        migrations.AlterField(
            model_name='s_payment',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 22, 48, 0, 491153)),
        ),
        migrations.AlterField(
            model_name='skills',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 22, 48, 0, 484154)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 22, 48, 0, 487155)),
        ),
    ]
